version: '2'
services:
  service-discovery:
    build:
      context: .
    ports:
      - "8081:8081"
    networks:
      - project-network

  server-gateway:
    build:
      context: https://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@github.com/project-smart-contract/server_gateway.git
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8081/eureka
    depends_on:
      - service-discovery
    networks:
      - project-network

  microservice1-auth:
    build:
      context: https://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@github.com/project-smart-contract/microservice1-auth.git
    ports:
      - "8082:8082"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8081/eureka
    depends_on:
      - service-discovery
      - server-gateway
    networks:
      - project-network

  microservice2-client:
    build:
      context: https://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@github.com/project-smart-contract/microservice2-client.git
    ports:
      - "8083:8083"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8081/eureka
    depends_on:
      - service-discovery
      - server-gateway
    networks:
      - project-network

  microservice3-admin:
    build:
      context: https://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@github.com/project-smart-contract/microservice3-admin.git
    ports:
      - "8084:8084"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8081/eureka
    depends_on:
      - service-discovery
      - server-gateway
    networks:
      - project-network

  microservice4-java-ml:
    build:
      context: https://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@github.com/project-smart-contract/microservice4-java-ml.git
    ports:
      - "8085:8085"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-discovery:8081/eureka
    depends_on:
      - service-discovery
      - server-gateway
    networks:
      - project-network

networks:
  project-network:
    driver: bridge
