apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
        - name: service-discovery
          image: aminabakkali/service-discovery
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery
spec:
  type: LoadBalancer
  selector:
    app: service-discovery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081