kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: deployment-manager
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "services"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-deployment-manager-binding
  namespace: default
subjects:
  - kind: User
    name: jenkins@igneous-clover-409614.iam.gserviceaccount.com
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
        - name: service-discovery
          image: aminabakkali/service-discovery
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery
spec:
  type: LoadBalancer
  selector:
    app: service-discovery
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081